### PR TITLE
general: various enhancement

### PR DESCRIPTION
**Pull request by leseb**
* declare and assign variable content using implicit typing
* ImageName calls where shadowing the initial declaration so we just do
a re-assignement now
* do not use complex conditions structure when the function return a
bool
* add some log.Fatal instead of fmt.Print + os.Exit
* Use RgwPort and don't hardode 8000
* image pull, print a newline before any error

Signed-off-by: Sébastien Han <seb@redhat.com>

### CODE REVIEW

**Comment by ErwanAliasr1** [comment]
This commit is touching too much stuff which are unrelated to each-other.
1 commit = 1 issue to be fixed.

This kind of commit is a nightmare to backport/revert.

Please split it.

**Comment by leseb** [comment]
@ErwanAliasr1 better?

**Review by ErwanAliasr1 — CHANGES_REQUESTED** [review]
implicite -> implicit

**Review by ErwanAliasr1 — APPROVED** [review]

**Review by ErwanAliasr1 — APPROVED** [review]

**Review by ErwanAliasr1 — APPROVED** [review]

**Review by ErwanAliasr1 — APPROVED** [review]

**Review by ErwanAliasr1 — APPROVED** [review]

**Review by ErwanAliasr1 — COMMENTED** [review]
I'm not sure that fmt.Print() and log.Fatal() are going to the same output. One is surely on stdout while the other is surely on stderr. So this patch only works if stdout = stderr.

Why not log.Fatal("\n" + err) ?

**Comment by ErwanAliasr1** [comment]
@leseb Thanks for the update. That's seriously easier to understand/comment and better also for the project tracability & atomic reverting if needed.

**Comment by leseb** [comment]
@ErwanAliasr1 `log.Fatal("\n" + err) ` does not work.
Updated the commit title.

**Comment by ErwanAliasr1** [comment]
@leseb then use log.println() if you want to add an empty line. But is it then useful ?

**Comment by leseb** [comment]
@ErwanAliasr1 well this way the error has its own line, which makes the whole thing more readable.

**Review by ErwanAliasr1 — APPROVED** [review]

**Pull request merged**
